/* Auto-generated by src/gen_config_accessors.py — do not edit directly.
 *
 * One accessor per config_t field. config_t is ~750 KB and its layout is a
 * config-module secret; callers outside the module ask for the value they
 * want and never name the type. Each reads a single field out of the live
 * snapshot under a reader pin, so a caller pays for one field rather than a
 * whole-struct copy.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "config.h"
#include "config_accessors.h"

/* Defined in config.c: reads one field out of the pinned snapshot, falling
 * back to a heap-loaded config when no snapshot is live. */
int config_field_read(size_t offset, size_t size, void *dst);

const char *config_prompt_tier(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, prompt_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_prompt_file(void)
{
   static _Thread_local char buf[MAX_PATH_LEN];
   buf[0] = 0;
   config_field_read(offsetof(config_t, prompt_file), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_delegate_prompt_tier(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, delegate_prompt_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_otel_endpoint(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, otel_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_otel_service_name(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, otel_service_name), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_mcp_osv_endpoint(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, mcp_osv_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_computer_use_default_navigation(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, computer_use_default_navigation), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_proxy_url(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, proxy_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_proxy_token(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, proxy_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_ingress_trusted_proxy_secret(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, ingress_trusted_proxy_secret), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_guardrails_semantic_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, guardrails_semantic_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_guardrails_semantic_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, guardrails_semantic_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_api_bearer_token(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_api_bearer_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_telemetry_metrics_token(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, telemetry_metrics_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_client_url(void)
{
   static _Thread_local char buf[CONFIG_DB2_URL_LEN];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_client_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_client_bearer_token(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_client_bearer_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_aimee_with_llamacpp(void)
{
   static _Thread_local char buf[8];
   buf[0] = 0;
   config_field_read(offsetof(config_t, aimee_with_llamacpp), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_aimee_synthesis_model(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, aimee_synthesis_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_synthesis_endpoint(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, synthesis_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_synthesis_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, synthesis_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_synthesis_api_key(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, synthesis_api_key), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_server_api_mtls_client_ca(void)
{
   static _Thread_local char buf[MAX_PATH_LEN];
   buf[0] = 0;
   config_field_read(offsetof(config_t, server_api_mtls_client_ca), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_server_api_bearer_token(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, server_api_bearer_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_server_api_client_transport(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, server_api_client_transport), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_calibration_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, calibration_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_calibration_prompt_version(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, calibration_prompt_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_calibration_model_version(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, calibration_model_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_fusion_mode(void)
{
   static _Thread_local char buf[32];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_fusion_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_ranker_fuse_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, ranker_fuse_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_ranker_fit_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_ranker_fit_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_ranker_fit_benchmark(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_ranker_fit_benchmark), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_ranker_fit_objective(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_ranker_fit_objective), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_reasoning_datalog_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, reasoning_datalog_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_bandit_optimize_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, bandit_optimize_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_planner_search_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, planner_search_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_constraint_solver_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, constraint_solver_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_synthesize_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_synthesize_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_trigger_auth_token(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, trigger_auth_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_tier(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_extract_prompt_version(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_extract_prompt_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_embed_model_version(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_embed_model_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_invalidation_notify_socket(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_invalidation_notify_socket), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_extract_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_extract_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_stage_order(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_stage_order), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_user_presets(void)
{
   static _Thread_local char buf[4096];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_user_presets), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_custom_stages(void)
{
   static _Thread_local char buf[4096];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_custom_stages), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_provider_base_url(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_provider_base_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_provider_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_provider_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_provider_api_key(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_provider_api_key), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_judge_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_judge_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_curator_synthesize_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_curator_synthesize_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_aux_default_provider(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, aux_default_provider), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_aux_default_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, aux_default_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_db2_vector_corpus_index(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, db2_vector_corpus_index), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_ensemble_aggregator(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, ensemble_aggregator), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_roundtable_turns(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, roundtable_turns), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_roundtable_default(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, roundtable_default), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_roundtable_pipeline_done_bar(void)
{
   static _Thread_local char buf[40];
   buf[0] = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_done_bar), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_context_engine(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, context_engine), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

size_t config_db1_path_copy(char *out, size_t n)
{
   char buf[MAX_PATH_LEN];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, db1_path), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_db2_url_copy(char *out, size_t n)
{
   char buf[CONFIG_DB2_URL_LEN];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, db2_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_provider_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, provider), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_default_persona_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, default_persona), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_claude_model_copy(char *out, size_t n)
{
   char buf[128];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, claude_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_codex_model_copy(char *out, size_t n)
{
   char buf[128];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, codex_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_model_reasoning_effort_copy(char *out, size_t n)
{
   char buf[32];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, model_reasoning_effort), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_openai_endpoint_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, openai_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_openai_model_copy(char *out, size_t n)
{
   char buf[128];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, openai_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_openai_key_cmd_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, openai_key_cmd), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_embedder_model_copy(char *out, size_t n)
{
   char buf[128];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, embedder_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_embedder_url_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, embedder_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_embedder_api_key_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, embedder_api_key), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_memory_weight_profile_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, memory_weight_profile), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_memory_rerank_mode_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, memory_rerank_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_css_render_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, css_render_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_vault_custody_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, vault_custody), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_vault_tpm2_blob_path_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, vault_tpm2_blob_path), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_vault_tpm2_tcti_copy(char *out, size_t n)
{
   char buf[128];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, vault_tpm2_tcti), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_vault_tpm2_nv_index_copy(char *out, size_t n)
{
   char buf[32];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, vault_tpm2_nv_index), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_memory_coref_mode_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, memory_coref_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_memory_cognify_model_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, memory_cognify_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_memory_cognify_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, memory_cognify_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_code_context_mode_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, code_context_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_session_worktree_base_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, session_worktree_base), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_delegate_sandbox_image_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, delegate_sandbox_image), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_delegate_sandbox_package_access_copy(char *out, size_t n)
{
   char buf[32];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, delegate_sandbox_package_access), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_pdf_tier_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_pdf_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_tsr_command_copy(char *out, size_t n)
{
   char buf[1024];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, tsr_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_pdf_blob_dir_copy(char *out, size_t n)
{
   char buf[1024];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_pdf_blob_dir), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_ocr_command_copy(char *out, size_t n)
{
   char buf[1024];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, ocr_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_memory_pagerank_relations_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, memory_pagerank_relations), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_memory_citations_mode_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, memory_citations_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_memory_rewrite_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, memory_rewrite_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_memory_query_expansion_mode_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, memory_query_expansion_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_memory_recall_lanes_summary_kinds_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, memory_recall_lanes_summary_kinds), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_memory_recall_lanes_fact_kinds_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, memory_recall_lanes_fact_kinds), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_memory_hard_negative_log_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, memory_hard_negative_log), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_dogfood_log_dir_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, dogfood_log_dir), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_learning_synthesize_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, learning_synthesize_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_learning_embed_model_version_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, learning_embed_model_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_learning_synthesize_prompt_version_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, learning_synthesize_prompt_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_verify_cmd_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, verify_cmd), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_verify_role_copy(char *out, size_t n)
{
   char buf[32];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, verify_role), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_verify_prompt_copy(char *out, size_t n)
{
   char buf[2048];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, verify_prompt), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_search_backend_copy(char *out, size_t n)
{
   char buf[32];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, search_backend), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_search_searxng_url_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, search_searxng_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_search_tavily_api_key_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, search_tavily_api_key), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_search_backends_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, search_backends), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_coord_closet_denylist_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, coord_closet_denylist), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_prompt_tier_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, prompt_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_prompt_file_copy(char *out, size_t n)
{
   char buf[MAX_PATH_LEN];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, prompt_file), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_delegate_prompt_tier_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, delegate_prompt_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_otel_endpoint_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, otel_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_otel_service_name_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, otel_service_name), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_mcp_osv_endpoint_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, mcp_osv_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_computer_use_default_navigation_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, computer_use_default_navigation), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_proxy_url_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, proxy_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_proxy_token_copy(char *out, size_t n)
{
   char buf[128];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, proxy_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_ingress_trusted_proxy_secret_copy(char *out, size_t n)
{
   char buf[128];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, ingress_trusted_proxy_secret), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_guardrails_semantic_mode_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, guardrails_semantic_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_guardrails_semantic_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, guardrails_semantic_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_api_bearer_token_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_api_bearer_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_telemetry_metrics_token_copy(char *out, size_t n)
{
   char buf[128];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, telemetry_metrics_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_client_url_copy(char *out, size_t n)
{
   char buf[CONFIG_DB2_URL_LEN];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_client_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_client_bearer_token_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_client_bearer_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_mode_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_aimee_with_llamacpp_copy(char *out, size_t n)
{
   char buf[8];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, aimee_with_llamacpp), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_aimee_synthesis_model_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, aimee_synthesis_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_synthesis_endpoint_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, synthesis_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_synthesis_model_copy(char *out, size_t n)
{
   char buf[128];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, synthesis_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_synthesis_api_key_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, synthesis_api_key), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_server_api_mtls_client_ca_copy(char *out, size_t n)
{
   char buf[MAX_PATH_LEN];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, server_api_mtls_client_ca), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_server_api_bearer_token_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, server_api_bearer_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_server_api_client_transport_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, server_api_client_transport), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_calibration_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, calibration_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_calibration_prompt_version_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, calibration_prompt_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_calibration_model_version_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, calibration_model_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_fusion_mode_copy(char *out, size_t n)
{
   char buf[32];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_fusion_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_ranker_fuse_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, ranker_fuse_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}
