/* Auto-generated by src/gen_config_accessors.py — do not edit directly.
 *
 * One accessor per config_t field. config_t is ~750 KB and its layout is a
 * config-module secret; callers outside the module ask for the value they
 * want and never name the type. Each reads a single field out of the live
 * snapshot under a reader pin, so a caller pays for one field rather than a
 * whole-struct copy.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "config.h"
#include "config_accessors.h"

/* Defined in config.c: reads one field out of the pinned snapshot, falling
 * back to a heap-loaded config when no snapshot is live. */
int config_field_read(size_t offset, size_t size, void *dst);

int config_db2_pool_size(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, db2_pool_size), sizeof(v), &v);
   return v;
}

int config_workspace_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, workspace_count), sizeof(v), &v);
   return v;
}

int config_subagent_ban_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, subagent_ban_enabled), sizeof(v), &v);
   return v;
}

int config_embedder_dims(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, embedder_dims), sizeof(v), &v);
   return v;
}

int config_memory_maintenance_trigger_inserts(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_maintenance_trigger_inserts), sizeof(v), &v);
   return v;
}

int config_memory_maintenance_trigger_secs(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_maintenance_trigger_secs), sizeof(v), &v);
   return v;
}

int config_memory_maintenance_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_maintenance_enabled), sizeof(v), &v);
   return v;
}

int config_memory_maintenance_interval_seconds(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_maintenance_interval_seconds), sizeof(v), &v);
   return v;
}

int config_memory_maintenance_summarize_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_maintenance_summarize_enabled), sizeof(v), &v);
   return v;
}

int config_code_cochange_git_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, code_cochange_git_enabled), sizeof(v), &v);
   return v;
}

int config_wfe_proposals_autoscan_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, wfe_proposals_autoscan_enabled), sizeof(v), &v);
   return v;
}

int config_client_integrations_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, client_integrations_enabled), sizeof(v), &v);
   return v;
}

int config_audit_action_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, audit_action_enabled), sizeof(v), &v);
   return v;
}

int config_memory_salience_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_salience_enabled), sizeof(v), &v);
   return v;
}

double config_memory_salience_weight(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, memory_salience_weight), sizeof(v), &v);
   return v;
}

int config_memory_salience_window_size(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_salience_window_size), sizeof(v), &v);
   return v;
}

int config_memory_surprise_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_surprise_enabled), sizeof(v), &v);
   return v;
}

double config_memory_surprise_weight(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, memory_surprise_weight), sizeof(v), &v);
   return v;
}

int config_memory_coref_window(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_coref_window), sizeof(v), &v);
   return v;
}

int config_memory_cognify_async_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_cognify_async_enabled), sizeof(v), &v);
   return v;
}

int config_memory_cognify_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_cognify_enabled), sizeof(v), &v);
   return v;
}

int config_memory_context_budget_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_context_budget_enabled), sizeof(v), &v);
   return v;
}

int config_memory_context_budget_tokens(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_context_budget_tokens), sizeof(v), &v);
   return v;
}

int config_ingress_preinject_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ingress_preinject_enabled), sizeof(v), &v);
   return v;
}

int config_ingress_preinject_anthropic_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ingress_preinject_anthropic_enabled), sizeof(v), &v);
   return v;
}

int config_ingress_preinject_assembly_budget(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ingress_preinject_assembly_budget), sizeof(v), &v);
   return v;
}

int config_ingress_max_raw_scans(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ingress_max_raw_scans), sizeof(v), &v);
   return v;
}

int config_code_span_max_lines(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, code_span_max_lines), sizeof(v), &v);
   return v;
}

int config_tool_output_max_bytes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, tool_output_max_bytes), sizeof(v), &v);
   return v;
}

int config_ingress_compress_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ingress_compress_enabled), sizeof(v), &v);
   return v;
}

int config_ingress_compress_min_chars(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ingress_compress_min_chars), sizeof(v), &v);
   return v;
}

int config_ingress_cache_placement_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ingress_cache_placement_enabled), sizeof(v), &v);
   return v;
}

int config_require_session_worktree(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, require_session_worktree), sizeof(v), &v);
   return v;
}

int config_require_aimee_memory(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, require_aimee_memory), sizeof(v), &v);
   return v;
}

int config_require_aimee_git(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, require_aimee_git), sizeof(v), &v);
   return v;
}

int config_delegate_sandbox(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, delegate_sandbox), sizeof(v), &v);
   return v;
}

int config_delegate_sandbox_require_isolation(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, delegate_sandbox_require_isolation), sizeof(v), &v);
   return v;
}

int config_delegate_sandbox_learn_packages(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, delegate_sandbox_learn_packages), sizeof(v), &v);
   return v;
}

int config_gateway_prevent_subagents(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, gateway_prevent_subagents), sizeof(v), &v);
   return v;
}

int config_gateway_pin_model(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, gateway_pin_model), sizeof(v), &v);
   return v;
}

int config_kb_typed_facts_auto_promote_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_typed_facts_auto_promote_enabled), sizeof(v), &v);
   return v;
}

int config_kb_typed_facts_promote_threshold(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_typed_facts_promote_threshold), sizeof(v), &v);
   return v;
}

int config_kb_pdf_ingest_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_pdf_ingest_enabled), sizeof(v), &v);
   return v;
}

int config_kb_pdf_tsr_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_pdf_tsr_enabled), sizeof(v), &v);
   return v;
}

int config_kb_pdf_assets_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_pdf_assets_enabled), sizeof(v), &v);
   return v;
}

int config_kb_pdf_blob_recon_secs(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_pdf_blob_recon_secs), sizeof(v), &v);
   return v;
}

int config_kb_pdf_blob_orphan_alarm_mb(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_pdf_blob_orphan_alarm_mb), sizeof(v), &v);
   return v;
}

int config_kb_pdf_ocr_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_pdf_ocr_enabled), sizeof(v), &v);
   return v;
}

int config_kb_evidence_emit_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_evidence_emit_enabled), sizeof(v), &v);
   return v;
}

int config_fidelity_check_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, fidelity_check_enabled), sizeof(v), &v);
   return v;
}

int config_memory_pagerank_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_pagerank_enabled), sizeof(v), &v);
   return v;
}

int config_memory_pagerank_iterations(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_pagerank_iterations), sizeof(v), &v);
   return v;
}

double config_memory_pagerank_weight(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, memory_pagerank_weight), sizeof(v), &v);
   return v;
}

int config_memory_citations_reprompt_on_miss(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_citations_reprompt_on_miss), sizeof(v), &v);
   return v;
}

int config_memory_citations_strip_unverified(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_citations_strip_unverified), sizeof(v), &v);
   return v;
}

int config_memory_briefing_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_briefing_enabled), sizeof(v), &v);
   return v;
}

int config_memory_briefing_limit_tokens(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_briefing_limit_tokens), sizeof(v), &v);
   return v;
}

int config_memory_aggregation_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_aggregation_enabled), sizeof(v), &v);
   return v;
}

int config_memory_aggregation_max_items(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_aggregation_max_items), sizeof(v), &v);
   return v;
}

int config_memory_prospective_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_prospective_enabled), sizeof(v), &v);
   return v;
}

int config_memory_prospective_max_matches(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_prospective_max_matches), sizeof(v), &v);
   return v;
}

int config_memory_lifecycle_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_lifecycle_enabled), sizeof(v), &v);
   return v;
}

int config_memory_lifecycle_hide_archived(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_lifecycle_hide_archived), sizeof(v), &v);
   return v;
}

int config_memory_lifecycle_ttl_date_days(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_lifecycle_ttl_date_days), sizeof(v), &v);
   return v;
}

int config_memory_lifecycle_ttl_relative_days(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_lifecycle_ttl_relative_days), sizeof(v), &v);
   return v;
}

int config_memory_lifecycle_ttl_open_ended_days(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_lifecycle_ttl_open_ended_days), sizeof(v), &v);
   return v;
}

int config_memory_recall_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_recall_enabled), sizeof(v), &v);
   return v;
}

int config_memory_recall_limit_tokens_session(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_recall_limit_tokens_session), sizeof(v), &v);
   return v;
}

int config_memory_recall_limit_tokens_turn(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_recall_limit_tokens_turn), sizeof(v), &v);
   return v;
}

int config_memory_directives_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_directives_enabled), sizeof(v), &v);
   return v;
}

int config_memory_directives_failure_threshold(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_directives_failure_threshold), sizeof(v), &v);
   return v;
}

int config_memory_directives_max_matches(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_directives_max_matches), sizeof(v), &v);
   return v;
}

int config_disposition_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, disposition_count), sizeof(v), &v);
   return v;
}

int config_disposition_global_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, disposition_global_count), sizeof(v), &v);
   return v;
}

int config_disposition_workspace_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, disposition_workspace_count), sizeof(v), &v);
   return v;
}

int config_disposition_project_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, disposition_project_count), sizeof(v), &v);
   return v;
}

int config_charter_safety_axioms_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, charter_safety_axioms_count), sizeof(v), &v);
   return v;
}

int config_charter_hard_constraints_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, charter_hard_constraints_count), sizeof(v), &v);
   return v;
}

int config_charter_values_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, charter_values_count), sizeof(v), &v);
   return v;
}

int config_charter_tone_boundaries_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, charter_tone_boundaries_count), sizeof(v), &v);
   return v;
}

int config_charter_working_profile_drift_limit(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, charter_working_profile_drift_limit), sizeof(v), &v);
   return v;
}

int config_identity_working_profile_injection_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, identity_working_profile_injection_enabled), sizeof(v), &v);
   return v;
}

int config_identity_working_profile_injection_fields_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, identity_working_profile_injection_fields_count), sizeof(v),
                     &v);
   return v;
}

int config_memory_profile_cards_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_profile_cards_enabled), sizeof(v), &v);
   return v;
}

int config_memory_profile_cards_min_obs(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_profile_cards_min_obs), sizeof(v), &v);
   return v;
}

int config_memory_profile_cards_stale_secs(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_profile_cards_stale_secs), sizeof(v), &v);
   return v;
}

int config_memory_rewrite_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_rewrite_enabled), sizeof(v), &v);
   return v;
}

int config_memory_rewrite_hyde(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_rewrite_hyde), sizeof(v), &v);
   return v;
}

int config_memory_rewrite_decompose(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_rewrite_decompose), sizeof(v), &v);
   return v;
}

int config_memory_rewrite_max_subqueries(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_rewrite_max_subqueries), sizeof(v), &v);
   return v;
}

int config_memory_window_radius(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_window_radius), sizeof(v), &v);
   return v;
}

int config_kb_search_max_results(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_search_max_results), sizeof(v), &v);
   return v;
}

int config_memory_negation_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_negation_enabled), sizeof(v), &v);
   return v;
}

int config_memory_query_expansion_k(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_query_expansion_k), sizeof(v), &v);
   return v;
}

int config_memory_recall_lanes_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_recall_lanes_enabled), sizeof(v), &v);
   return v;
}

int config_memory_recall_lanes_k_summary(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_recall_lanes_k_summary), sizeof(v), &v);
   return v;
}

int config_memory_recall_lanes_k_fact(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_recall_lanes_k_fact), sizeof(v), &v);
   return v;
}

int config_memory_recall_lanes_floor_summary(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_recall_lanes_floor_summary), sizeof(v), &v);
   return v;
}

int config_memory_recall_lanes_floor_fact(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_recall_lanes_floor_fact), sizeof(v), &v);
   return v;
}

int config_memory_improve_dedupe_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_improve_dedupe_enabled), sizeof(v), &v);
   return v;
}

int config_memory_improve_summarise_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_improve_summarise_enabled), sizeof(v), &v);
   return v;
}

int config_memory_improve_min_cluster(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_improve_min_cluster), sizeof(v), &v);
   return v;
}

double config_memory_improve_max_confidence(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, memory_improve_max_confidence), sizeof(v), &v);
   return v;
}

int config_memory_episode_summaries_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_episode_summaries_enabled), sizeof(v), &v);
   return v;
}

int config_memory_scenes_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_scenes_enabled), sizeof(v), &v);
   return v;
}

double config_memory_scenes_global_escape_ratio(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, memory_scenes_global_escape_ratio), sizeof(v), &v);
   return v;
}

int config_memory_failure_detection_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_failure_detection_enabled), sizeof(v), &v);
   return v;
}

double config_memory_failure_detection_threshold(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, memory_failure_detection_threshold), sizeof(v), &v);
   return v;
}

int config_memory_abstain_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_abstain_enabled), sizeof(v), &v);
   return v;
}

double config_memory_abstain_gate(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, memory_abstain_gate), sizeof(v), &v);
   return v;
}

double config_memory_chunk_min_confidence(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, memory_chunk_min_confidence), sizeof(v), &v);
   return v;
}

double config_memory_bm25_weight(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, memory_bm25_weight), sizeof(v), &v);
   return v;
}

double config_memory_semantic_weight(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, memory_semantic_weight), sizeof(v), &v);
   return v;
}

int config_memory_fetch_budget_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_fetch_budget_enabled), sizeof(v), &v);
   return v;
}

int config_memory_fetch_budget_base(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_fetch_budget_base), sizeof(v), &v);
   return v;
}

int config_memory_fetch_budget_shape_aware(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, memory_fetch_budget_shape_aware), sizeof(v), &v);
   return v;
}

int config_dogfood_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, dogfood_enabled), sizeof(v), &v);
   return v;
}

int config_dogfood_commit_raw(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, dogfood_commit_raw), sizeof(v), &v);
   return v;
}

int config_dogfood_inline_tagging(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, dogfood_inline_tagging), sizeof(v), &v);
   return v;
}

int config_dogfood_autolabel_repair(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, dogfood_autolabel_repair), sizeof(v), &v);
   return v;
}

int config_dogfood_autolabel_continuation(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, dogfood_autolabel_continuation), sizeof(v), &v);
   return v;
}

int config_dogfood_autolabel_repeat_question(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, dogfood_autolabel_repeat_question), sizeof(v), &v);
   return v;
}

int config_learning_router_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, learning_router_enabled), sizeof(v), &v);
   return v;
}

int config_learning_proposal_ttl_days(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, learning_proposal_ttl_days), sizeof(v), &v);
   return v;
}

int config_learning_max_commits_per_week(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, learning_max_commits_per_week), sizeof(v), &v);
   return v;
}

int config_learning_synthesize_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, learning_synthesize_enabled), sizeof(v), &v);
   return v;
}

int config_learning_synthesize_max_tokens(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, learning_synthesize_max_tokens), sizeof(v), &v);
   return v;
}

int config_learning_synthesize_k(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, learning_synthesize_k), sizeof(v), &v);
   return v;
}

int config_learning_implicit_citation_repair(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, learning_implicit_citation_repair), sizeof(v), &v);
   return v;
}

int config_learning_implicit_citation_continuation(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, learning_implicit_citation_continuation), sizeof(v), &v);
   return v;
}

int config_learning_implicit_repeat_question(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, learning_implicit_repeat_question), sizeof(v), &v);
   return v;
}

int config_learning_implicit_repeated_correction(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, learning_implicit_repeated_correction), sizeof(v), &v);
   return v;
}

int config_learning_implicit_workflow_repetition(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, learning_implicit_workflow_repetition), sizeof(v), &v);
   return v;
}

int config_learning_implicit_retrieval_outcome(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, learning_implicit_retrieval_outcome), sizeof(v), &v);
   return v;
}

int config_autonomous(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, autonomous), sizeof(v), &v);
   return v;
}

int config_verify_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, verify_enabled), sizeof(v), &v);
   return v;
}

int config_roundtable_replay_verify_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_replay_verify_enabled), sizeof(v), &v);
   return v;
}

int config_roundtable_require_evidence(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_require_evidence), sizeof(v), &v);
   return v;
}

int config_roundtable_chair_synthesis(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_chair_synthesis), sizeof(v), &v);
   return v;
}

int config_verify_cross_project(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, verify_cross_project), sizeof(v), &v);
   return v;
}
