/* Auto-generated by src/gen_config_accessors.py — do not edit directly.
 *
 * One accessor per config_t field. config_t is ~750 KB and its layout is a
 * config-module secret; callers outside the module ask for the value they
 * want and never name the type. Each reads a single field out of the live
 * snapshot under a reader pin, so a caller pays for one field rather than a
 * whole-struct copy.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "config.h"
#include "config_accessors.h"

/* Defined in config.c: reads one field out of the pinned snapshot, falling
 * back to a heap-loaded config when no snapshot is live. */
int config_field_read(size_t offset, size_t size, void *dst);

int config_set_memory_recall_lanes_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_recall_lanes_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_recall_lanes_k_summary(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_recall_lanes_k_summary = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_recall_lanes_k_fact(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_recall_lanes_k_fact = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_recall_lanes_floor_summary(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_recall_lanes_floor_summary = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_recall_lanes_floor_fact(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_recall_lanes_floor_fact = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_improve_dedupe_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_improve_dedupe_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_improve_summarise_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_improve_summarise_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_improve_min_cluster(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_improve_min_cluster = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_improve_max_confidence(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_improve_max_confidence = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_episode_summaries_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_episode_summaries_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_scenes_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_scenes_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_scenes_global_escape_ratio(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_scenes_global_escape_ratio = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_failure_detection_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_failure_detection_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_failure_detection_threshold(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_failure_detection_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_abstain_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_abstain_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_abstain_gate(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_abstain_gate = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_chunk_min_confidence(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_chunk_min_confidence = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_bm25_weight(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_bm25_weight = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_semantic_weight(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_semantic_weight = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_fetch_budget_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_fetch_budget_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_fetch_budget_base(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_fetch_budget_base = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_fetch_budget_shape_aware(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_fetch_budget_shape_aware = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_dogfood_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->dogfood_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_dogfood_commit_raw(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->dogfood_commit_raw = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_dogfood_inline_tagging(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->dogfood_inline_tagging = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_dogfood_autolabel_repair(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->dogfood_autolabel_repair = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_dogfood_autolabel_continuation(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->dogfood_autolabel_continuation = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_dogfood_autolabel_repeat_question(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->dogfood_autolabel_repeat_question = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_router_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->learning_router_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_proposal_ttl_days(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->learning_proposal_ttl_days = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_max_commits_per_week(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->learning_max_commits_per_week = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_synthesize_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->learning_synthesize_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_synthesize_max_tokens(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->learning_synthesize_max_tokens = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_synthesize_k(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->learning_synthesize_k = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_implicit_citation_repair(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->learning_implicit_citation_repair = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_implicit_citation_continuation(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->learning_implicit_citation_continuation = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_implicit_repeat_question(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->learning_implicit_repeat_question = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_implicit_repeated_correction(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->learning_implicit_repeated_correction = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_implicit_workflow_repetition(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->learning_implicit_workflow_repetition = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_implicit_retrieval_outcome(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->learning_implicit_retrieval_outcome = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_autonomous(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->autonomous = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_verify_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->verify_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_replay_verify_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_replay_verify_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_require_evidence(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_require_evidence = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_chair_synthesis(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_chair_synthesis = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_verify_cross_project(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->verify_cross_project = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_cross_verify(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->cross_verify = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_retry_max_attempts(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->retry_max_attempts = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_retry_base_ms(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->retry_base_ms = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_retry_max_ms(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->retry_max_ms = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_max_iterations(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->max_iterations = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_max_iterations_delegate(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->max_iterations_delegate = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_max_delegation_depth(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->max_delegation_depth = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_max_delegation_spawns(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->max_delegation_spawns = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_compute_threads(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->compute_threads = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_session_threads(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->session_threads = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_delegate_max_inflight(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->delegate_max_inflight = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_maximum_total_concurrent_agent_sessions(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->maximum_total_concurrent_agent_sessions = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_concurrency_default(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->concurrency_default = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_concurrency_per_model_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->concurrency_per_model_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_concurrency_per_provider_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->concurrency_per_provider_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_concurrency_preempt_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->concurrency_preempt_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_concurrency_preempt_single_slot_only(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->concurrency_preempt_single_slot_only = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_concurrency_preempt_requeue_max(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->concurrency_preempt_requeue_max = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_search_max_results(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->search_max_results = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_search_fetch_pages(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->search_fetch_pages = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_compact_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->compact_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_compact_threshold(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->compact_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_compact_head_bytes(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->compact_head_bytes = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_compact_tail_bytes(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->compact_tail_bytes = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_compact_per_tool_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->compact_per_tool_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_coord_closet_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->coord_closet_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_coord_closet_budget_bytes(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->coord_closet_budget_bytes = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_coord_closet_max_ratio_pct(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->coord_closet_max_ratio_pct = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_fold_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->fold_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_fold_retained_msgs(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->fold_retained_msgs = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_fold_min_fold_msgs(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->fold_min_fold_msgs = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_fold_excerpt_bytes(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->fold_excerpt_bytes = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_fold_register_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->fold_register_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_fold_freeze_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->fold_freeze_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_fold_freeze_tail_cap_msgs(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->fold_freeze_tail_cap_msgs = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_fold_recall_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->fold_recall_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_fold_recall_ttl_turns(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->fold_recall_ttl_turns = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_economizer_mode(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->economizer_mode = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_module_memory(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->module_memory = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_module_governance(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->module_governance = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_module_delegates(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->module_delegates = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_module_workflows(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->module_workflows = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_module_roundtable(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->module_roundtable = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_module_economizer(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->module_economizer = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_autonomy_skeptics(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->autonomy_skeptics = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_autonomy_fanout(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->autonomy_fanout = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_autonomy_unit_retry(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->autonomy_unit_retry = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_autonomy_unit_max(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->autonomy_unit_max = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_autonomy_ci_retry_max(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->autonomy_ci_retry_max = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_autonomy_max_turns(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->autonomy_max_turns = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_autonomy_max_wall_secs(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->autonomy_max_wall_secs = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_autonomy_stale_abandon_secs(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->autonomy_stale_abandon_secs = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_autonomy_concurrency(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->autonomy_concurrency = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_autonomy_auto_resume_cap_parks(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->autonomy_auto_resume_cap_parks = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_autonomy_max_resumes(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->autonomy_max_resumes = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_worktree_stale_secs(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->worktree_stale_secs = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_max_sessions(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->max_sessions = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_max_worktrees(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->max_worktrees = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_max_background_processes(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->max_background_processes = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_rewind_auto_snapshot(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->rewind_auto_snapshot = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_lsp_server_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->lsp_server_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_mcp_client_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->mcp_client_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_mcp_osv_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->mcp_osv_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_mcp_osv_offline(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->mcp_osv_offline = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_mcp_osv_enforce(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->mcp_osv_enforce = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_mcp_osv_cache_ttl_hours(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->mcp_osv_cache_ttl_hours = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_mcp_osv_allow_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->mcp_osv_allow_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_computer_use_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->computer_use_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_computer_use_redact_sensitive_screenshots(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->computer_use_redact_sensitive_screenshots = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_computer_use_allowed_domain_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->computer_use_allowed_domain_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_integrity_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->integrity_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_integrity_dry_run(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->integrity_dry_run = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_virtual_context_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->virtual_context_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_virtual_context_assembly_budget(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->virtual_context_assembly_budget = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_cache_aware_rewrite_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->cache_aware_rewrite_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_cache_aware_rewrite_min_savings_tokens(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->cache_aware_rewrite_min_savings_tokens = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_cache_aware_rewrite_hard_context_threshold(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->cache_aware_rewrite_hard_context_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_cache_aware_rewrite_max_defer_turns(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->cache_aware_rewrite_max_defer_turns = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_cache_aware_rewrite_segment_check_turns(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->cache_aware_rewrite_segment_check_turns = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_transport_server_keepalive_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->transport_server_keepalive_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_transport_thinclient_gzip_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->transport_thinclient_gzip_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_transport_kb_gzip_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->transport_kb_gzip_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_cost_reward_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->cost_reward_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_cost_reward_lambda_pct(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->cost_reward_lambda_pct = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_cost_reward_ref_usd_milli(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->cost_reward_ref_usd_milli = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_reasoning_cap_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->reasoning_cap_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_dedup_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->dedup_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_cache_shaping_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->cache_shaping_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_dedup_window_seconds(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->dedup_window_seconds = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_cache_min_chars(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->cache_min_chars = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_guardrails_semantic_warn_threshold(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->guardrails_semantic_warn_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_guardrails_semantic_prompt_threshold(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->guardrails_semantic_prompt_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_guardrails_semantic_block_threshold(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->guardrails_semantic_block_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_api_http_port(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_api_http_port = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}
