/* Auto-generated by src/gen_config_accessors.py — do not edit directly.
 *
 * One accessor per config_t field. config_t is ~750 KB and its layout is a
 * config-module secret; callers outside the module ask for the value they
 * want and never name the type. Each reads a single field out of the live
 * snapshot under a reader pin, so a caller pays for one field rather than a
 * whole-struct copy.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "config.h"
#include "config_accessors.h"

/* Defined in config.c: reads one field out of the pinned snapshot, falling
 * back to a heap-loaded config when no snapshot is live. */
int config_field_read(size_t offset, size_t size, void *dst);

int config_kb_bg_ingest_interval_hours(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_bg_ingest_interval_hours), sizeof(v), &v);
   return v;
}

int config_kb_bg_watch_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_bg_watch_enabled), sizeof(v), &v);
   return v;
}

int config_kb_bg_watch_debounce_secs(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_bg_watch_debounce_secs), sizeof(v), &v);
   return v;
}

double config_code_hybrid_weight_code(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, code_hybrid_weight_code), sizeof(v), &v);
   return v;
}

double config_code_hybrid_weight_graph(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, code_hybrid_weight_graph), sizeof(v), &v);
   return v;
}

double config_code_hybrid_weight_vector(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, code_hybrid_weight_vector), sizeof(v), &v);
   return v;
}

double config_code_hybrid_weight_memory(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, code_hybrid_weight_memory), sizeof(v), &v);
   return v;
}

double config_code_hybrid_rrf_k(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, code_hybrid_rrf_k), sizeof(v), &v);
   return v;
}

int config_code_trust_actuation_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, code_trust_actuation_enabled), sizeof(v), &v);
   return v;
}

double config_code_surprising_precision_floor(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, code_surprising_precision_floor), sizeof(v), &v);
   return v;
}

int config_kb_reembed_on_dim_change(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_reembed_on_dim_change), sizeof(v), &v);
   return v;
}

int config_kb_purge_fence_ttl_s(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_purge_fence_ttl_s), sizeof(v), &v);
   return v;
}

int config_kb_maintenance_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_maintenance_enabled), sizeof(v), &v);
   return v;
}

int config_kb_maintenance_interval_hours(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_maintenance_interval_hours), sizeof(v), &v);
   return v;
}

double config_kb_maintenance_lambda(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, kb_maintenance_lambda), sizeof(v), &v);
   return v;
}

double config_kb_maintenance_floor(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, kb_maintenance_floor), sizeof(v), &v);
   return v;
}

int config_kb_maintenance_min_age_days(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_maintenance_min_age_days), sizeof(v), &v);
   return v;
}

int config_kb_maintenance_orphan_days(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_maintenance_orphan_days), sizeof(v), &v);
   return v;
}

int config_kb_mining_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_mining_enabled), sizeof(v), &v);
   return v;
}

int config_kb_mining_min_poll_s(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_mining_min_poll_s), sizeof(v), &v);
   return v;
}

int config_kb_mining_failure_learning_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_mining_failure_learning_enabled), sizeof(v), &v);
   return v;
}

int config_trigger_max_concurrent(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, trigger_max_concurrent), sizeof(v), &v);
   return v;
}

int config_trigger_rule_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, trigger_rule_count), sizeof(v), &v);
   return v;
}

int config_cron_job_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, cron_job_count), sizeof(v), &v);
   return v;
}

int config_review_scheduler_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, review_scheduler_enabled), sizeof(v), &v);
   return v;
}

int config_review_idle_trigger_minutes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, review_idle_trigger_minutes), sizeof(v), &v);
   return v;
}

int config_review_session_cooldown_hours(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, review_session_cooldown_hours), sizeof(v), &v);
   return v;
}

int config_review_batch_cap(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, review_batch_cap), sizeof(v), &v);
   return v;
}

int config_kb_curator_extract_docs_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_extract_docs_enabled), sizeof(v), &v);
   return v;
}

int config_kb_curator_extract_code_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_extract_code_enabled), sizeof(v), &v);
   return v;
}

int config_kb_curator_extract_code_workers(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_extract_code_workers), sizeof(v), &v);
   return v;
}

int config_kb_curator_extract_docs_workers(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_extract_docs_workers), sizeof(v), &v);
   return v;
}

int config_kb_curator_resolve_entities_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_resolve_entities_enabled), sizeof(v), &v);
   return v;
}

int config_kb_curator_index_narrative_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_index_narrative_enabled), sizeof(v), &v);
   return v;
}

int config_kb_curator_index_claims_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_index_claims_enabled), sizeof(v), &v);
   return v;
}

int config_kb_curator_detect_contradictions_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_detect_contradictions_enabled), sizeof(v), &v);
   return v;
}

int config_kb_curator_index_code_unit_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_index_code_unit_enabled), sizeof(v), &v);
   return v;
}

int config_kb_curator_link_artifacts_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_link_artifacts_enabled), sizeof(v), &v);
   return v;
}

int config_kb_curator_projection_graph_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_projection_graph_enabled), sizeof(v), &v);
   return v;
}

int config_kb_curator_synthesize_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_synthesize_enabled), sizeof(v), &v);
   return v;
}

int config_kb_curator_promote_entity_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_promote_entity_enabled), sizeof(v), &v);
   return v;
}

int config_kb_curator_promote_min_sources(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_promote_min_sources), sizeof(v), &v);
   return v;
}

int config_kb_curator_extract_max_tokens(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_extract_max_tokens), sizeof(v), &v);
   return v;
}

int config_kb_curator_max_attempts(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_max_attempts), sizeof(v), &v);
   return v;
}

int config_kb_curator_synthesize_k(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_synthesize_k), sizeof(v), &v);
   return v;
}

int config_kb_curator_cross_repo_graph_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_cross_repo_graph_enabled), sizeof(v), &v);
   return v;
}

int config_kb_curator_cross_repo_distinctiveness_v(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_cross_repo_distinctiveness_v), sizeof(v), &v);
   return v;
}

int config_kb_curator_cross_repo_k(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_cross_repo_k), sizeof(v), &v);
   return v;
}

int config_kb_curator_cross_repo_m(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_cross_repo_m), sizeof(v), &v);
   return v;
}

int config_kb_curator_cross_repo_p_pct(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_cross_repo_p_pct), sizeof(v), &v);
   return v;
}

int config_kb_curator_cross_repo_len_min(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_cross_repo_len_min), sizeof(v), &v);
   return v;
}

int config_kb_curator_cross_repo_caller_collision_c(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_cross_repo_caller_collision_c), sizeof(v), &v);
   return v;
}

int config_kb_curator_cross_repo_max_candidates(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_cross_repo_max_candidates), sizeof(v), &v);
   return v;
}

int config_kb_curator_cross_repo_query_timeout_ms(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_cross_repo_query_timeout_ms), sizeof(v), &v);
   return v;
}

int config_kb_curator_cross_repo_review_queue_max(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_curator_cross_repo_review_queue_max), sizeof(v), &v);
   return v;
}

int config_kb_evidence_embed_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_evidence_embed_enabled), sizeof(v), &v);
   return v;
}

int config_kb_evidence_embed_batch(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_evidence_embed_batch), sizeof(v), &v);
   return v;
}

int config_skills_review_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_review_enabled), sizeof(v), &v);
   return v;
}

int config_skills_review_nudge_interval(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_review_nudge_interval), sizeof(v), &v);
   return v;
}

int config_skills_stale_after_days(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_stale_after_days), sizeof(v), &v);
   return v;
}

int config_skills_archive_after_days(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_archive_after_days), sizeof(v), &v);
   return v;
}

int config_skills_dispatch_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_dispatch_enabled), sizeof(v), &v);
   return v;
}

int config_skills_dispatch_max_index(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_dispatch_max_index), sizeof(v), &v);
   return v;
}

int config_skills_dispatch_advisory(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_dispatch_advisory), sizeof(v), &v);
   return v;
}

int config_skills_capability_autostub(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_capability_autostub), sizeof(v), &v);
   return v;
}

int config_skills_eval_gate_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, skills_eval_gate_enabled), sizeof(v), &v);
   return v;
}

double config_skills_eval_threshold(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, skills_eval_threshold), sizeof(v), &v);
   return v;
}

int config_worktree_gc_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, worktree_gc_enabled), sizeof(v), &v);
   return v;
}

int config_worktree_gc_max_age_days(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, worktree_gc_max_age_days), sizeof(v), &v);
   return v;
}

int config_aux_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, aux_enabled), sizeof(v), &v);
   return v;
}

int config_aux_default_max_tokens(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, aux_default_max_tokens), sizeof(v), &v);
   return v;
}

int config_aux_task_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, aux_task_count), sizeof(v), &v);
   return v;
}

int config_prefer_local_agents(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, prefer_local_agents), sizeof(v), &v);
   return v;
}

int config_model_meta_refresh_minutes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, model_meta_refresh_minutes), sizeof(v), &v);
   return v;
}

int config_model_meta_capability_routing(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, model_meta_capability_routing), sizeof(v), &v);
   return v;
}

int64_t config_db2_vector_corpus_diskann_threshold(void)
{
   int64_t v = 0;
   config_field_read(offsetof(config_t, db2_vector_corpus_diskann_threshold), sizeof(v), &v);
   return v;
}

int config_ensemble_reference_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ensemble_reference_count), sizeof(v), &v);
   return v;
}

int config_ensemble_reference_persona_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ensemble_reference_persona_count), sizeof(v), &v);
   return v;
}

int config_ensemble_min_successful(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, ensemble_min_successful), sizeof(v), &v);
   return v;
}

double config_ensemble_max_cost_usd(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, ensemble_max_cost_usd), sizeof(v), &v);
   return v;
}

int config_roundtable_max_rounds(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_max_rounds), sizeof(v), &v);
   return v;
}

int config_roundtable_converge_threshold(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_converge_threshold), sizeof(v), &v);
   return v;
}

int config_roundtable_deadline_ms(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_deadline_ms), sizeof(v), &v);
   return v;
}

int config_roundtable_pipeline_max_passes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_max_passes), sizeof(v), &v);
   return v;
}

int config_roundtable_pipeline_max_attempts_per_pass(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_max_attempts_per_pass), sizeof(v), &v);
   return v;
}

double config_roundtable_pipeline_max_cost_usd(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_max_cost_usd), sizeof(v), &v);
   return v;
}

double config_roundtable_pipeline_max_total_cost_usd(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_max_total_cost_usd), sizeof(v), &v);
   return v;
}

int config_roundtable_pipeline_gate_ttl_h(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_gate_ttl_h), sizeof(v), &v);
   return v;
}

int config_roundtable_pipeline_parked_releases_slot(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_parked_releases_slot), sizeof(v), &v);
   return v;
}

int config_roundtable_pipeline_unknown_context_tokens(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_unknown_context_tokens), sizeof(v), &v);
   return v;
}

const char *config_db1_path(void)
{
   static _Thread_local char buf[MAX_PATH_LEN];
   buf[0] = 0;
   config_field_read(offsetof(config_t, db1_path), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_db2_url(void)
{
   static _Thread_local char buf[CONFIG_DB2_URL_LEN];
   buf[0] = 0;
   config_field_read(offsetof(config_t, db2_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_provider(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, provider), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_default_persona(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, default_persona), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_claude_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, claude_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_codex_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, codex_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_model_reasoning_effort(void)
{
   static _Thread_local char buf[32];
   buf[0] = 0;
   config_field_read(offsetof(config_t, model_reasoning_effort), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_openai_endpoint(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, openai_endpoint), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_openai_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, openai_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_openai_key_cmd(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, openai_key_cmd), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_embedder_model(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, embedder_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_embedder_url(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, embedder_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_embedder_api_key(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, embedder_api_key), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_weight_profile(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_weight_profile), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_rerank_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_rerank_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_css_render_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, css_render_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_vault_custody(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, vault_custody), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_vault_tpm2_blob_path(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, vault_tpm2_blob_path), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_vault_tpm2_tcti(void)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   config_field_read(offsetof(config_t, vault_tpm2_tcti), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_vault_tpm2_nv_index(void)
{
   static _Thread_local char buf[32];
   buf[0] = 0;
   config_field_read(offsetof(config_t, vault_tpm2_nv_index), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_coref_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_coref_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_cognify_model(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_cognify_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_cognify_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_cognify_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_code_context_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, code_context_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_session_worktree_base(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, session_worktree_base), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_delegate_sandbox_image(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, delegate_sandbox_image), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_delegate_sandbox_package_access(void)
{
   static _Thread_local char buf[32];
   buf[0] = 0;
   config_field_read(offsetof(config_t, delegate_sandbox_package_access), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_pdf_tier(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_pdf_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_tsr_command(void)
{
   static _Thread_local char buf[1024];
   buf[0] = 0;
   config_field_read(offsetof(config_t, tsr_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_kb_pdf_blob_dir(void)
{
   static _Thread_local char buf[1024];
   buf[0] = 0;
   config_field_read(offsetof(config_t, kb_pdf_blob_dir), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_ocr_command(void)
{
   static _Thread_local char buf[1024];
   buf[0] = 0;
   config_field_read(offsetof(config_t, ocr_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_pagerank_relations(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_pagerank_relations), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_citations_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_citations_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_rewrite_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_rewrite_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_query_expansion_mode(void)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_query_expansion_mode), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_recall_lanes_summary_kinds(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_recall_lanes_summary_kinds), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_recall_lanes_fact_kinds(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_recall_lanes_fact_kinds), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_memory_hard_negative_log(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, memory_hard_negative_log), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_dogfood_log_dir(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, dogfood_log_dir), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_learning_synthesize_command(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, learning_synthesize_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_learning_embed_model_version(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, learning_embed_model_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_learning_synthesize_prompt_version(void)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   config_field_read(offsetof(config_t, learning_synthesize_prompt_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_verify_cmd(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, verify_cmd), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_verify_role(void)
{
   static _Thread_local char buf[32];
   buf[0] = 0;
   config_field_read(offsetof(config_t, verify_role), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_verify_prompt(void)
{
   static _Thread_local char buf[2048];
   buf[0] = 0;
   config_field_read(offsetof(config_t, verify_prompt), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_search_backend(void)
{
   static _Thread_local char buf[32];
   buf[0] = 0;
   config_field_read(offsetof(config_t, search_backend), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_search_searxng_url(void)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   config_field_read(offsetof(config_t, search_searxng_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_search_tavily_api_key(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, search_tavily_api_key), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_search_backends(void)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   config_field_read(offsetof(config_t, search_backends), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}
