/* Auto-generated by src/gen_config_accessors.py — do not edit directly.
 *
 * One accessor per config_t field. config_t is ~750 KB and its layout is a
 * config-module secret; callers outside the module ask for the value they
 * want and never name the type. Each reads a single field out of the live
 * snapshot under a reader pin, so a caller pays for one field rather than a
 * whole-struct copy.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "config.h"
#include "config_accessors.h"

/* Defined in config.c: reads one field out of the pinned snapshot, falling
 * back to a heap-loaded config when no snapshot is live. */
int config_field_read(size_t offset, size_t size, void *dst);

size_t config_kb_ranker_fit_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_ranker_fit_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_ranker_fit_benchmark_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_ranker_fit_benchmark), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_ranker_fit_objective_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_ranker_fit_objective), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_reasoning_datalog_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, reasoning_datalog_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_bandit_optimize_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, bandit_optimize_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_planner_search_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, planner_search_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_constraint_solver_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, constraint_solver_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_synthesize_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_synthesize_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_trigger_auth_token_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, trigger_auth_token), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_tier_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_tier), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_extract_prompt_version_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_extract_prompt_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_embed_model_version_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_embed_model_version), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_invalidation_notify_socket_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_invalidation_notify_socket), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_extract_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_extract_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_stage_order_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_stage_order), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_user_presets_copy(char *out, size_t n)
{
   char buf[4096];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_user_presets), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_custom_stages_copy(char *out, size_t n)
{
   char buf[4096];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_custom_stages), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_provider_base_url_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_provider_base_url), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_provider_model_copy(char *out, size_t n)
{
   char buf[128];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_provider_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_provider_api_key_copy(char *out, size_t n)
{
   char buf[256];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_provider_api_key), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_judge_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_judge_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_kb_curator_synthesize_command_copy(char *out, size_t n)
{
   char buf[512];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, kb_curator_synthesize_command), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_aux_default_provider_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, aux_default_provider), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_aux_default_model_copy(char *out, size_t n)
{
   char buf[128];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, aux_default_model), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_db2_vector_corpus_index_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, db2_vector_corpus_index), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_ensemble_aggregator_copy(char *out, size_t n)
{
   char buf[128];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, ensemble_aggregator), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_roundtable_turns_copy(char *out, size_t n)
{
   char buf[16];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, roundtable_turns), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_roundtable_default_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, roundtable_default), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_roundtable_pipeline_done_bar_copy(char *out, size_t n)
{
   char buf[40];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, roundtable_pipeline_done_bar), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

size_t config_context_engine_copy(char *out, size_t n)
{
   char buf[64];
   if (!out || n == 0)
      return 0;
   config_field_read(offsetof(config_t, context_engine), sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   snprintf(out, n, "%s", buf);
   return sizeof(buf);
}

const char *config_workspaces(int index)
{
   static _Thread_local char buf[MAX_PATH_LEN];
   buf[0] = 0;
   if (index < 0 || index >= (64))
      return buf;
   config_field_read(offsetof(config_t, workspaces) + (size_t)index * sizeof(buf), sizeof(buf),
                     buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_workspace_providers(int index)
{
   static _Thread_local char buf[16];
   buf[0] = 0;
   if (index < 0 || index >= (64))
      return buf;
   config_field_read(offsetof(config_t, workspace_providers) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_workspace_vcs_remote(int index)
{
   static _Thread_local char buf[512];
   buf[0] = 0;
   if (index < 0 || index >= (64))
      return buf;
   config_field_read(offsetof(config_t, workspace_vcs_remote) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_workspace_vcs_head(int index)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   if (index < 0 || index >= (64))
      return buf;
   config_field_read(offsetof(config_t, workspace_vcs_head) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_workspace_sandbox_image(int index)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   if (index < 0 || index >= (64))
      return buf;
   config_field_read(offsetof(config_t, workspace_sandbox_image) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_charter_safety_axioms(int index)
{
   static _Thread_local char buf[CONFIG_CHARTER_ENTRY_LEN];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_CHARTER_MAX_ENTRIES))
      return buf;
   config_field_read(offsetof(config_t, charter_safety_axioms) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_charter_hard_constraints(int index)
{
   static _Thread_local char buf[CONFIG_CHARTER_ENTRY_LEN];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_CHARTER_MAX_ENTRIES))
      return buf;
   config_field_read(offsetof(config_t, charter_hard_constraints) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_charter_values(int index)
{
   static _Thread_local char buf[CONFIG_CHARTER_ENTRY_LEN];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_CHARTER_MAX_ENTRIES))
      return buf;
   config_field_read(offsetof(config_t, charter_values) + (size_t)index * sizeof(buf), sizeof(buf),
                     buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_charter_tone_boundaries(int index)
{
   static _Thread_local char buf[CONFIG_CHARTER_ENTRY_LEN];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_CHARTER_MAX_ENTRIES))
      return buf;
   config_field_read(offsetof(config_t, charter_tone_boundaries) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_identity_working_profile_injection_fields(int index)
{
   static _Thread_local char buf[CONFIG_WORKING_PROFILE_FIELD_LEN];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_WORKING_PROFILE_ALLOW_MAX))
      return buf;
   config_field_read(offsetof(config_t, identity_working_profile_injection_fields) +
                         (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_compact_per_tool(int index)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_COMPACT_MAX_PER_TOOL))
      return buf;
   config_field_read(offsetof(config_t, compact_per_tool) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_mcp_osv_allow(int index)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_MCP_OSV_MAX_ALLOW))
      return buf;
   config_field_read(offsetof(config_t, mcp_osv_allow) + (size_t)index * sizeof(buf), sizeof(buf),
                     buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_computer_use_allowed_domains(int index)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_COMPUTER_USE_MAX_DOMAINS))
      return buf;
   config_field_read(offsetof(config_t, computer_use_allowed_domains) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_server_api_bearer_extra(int index)
{
   static _Thread_local char buf[256];
   buf[0] = 0;
   if (index < 0 || index >= (AIMEE_API_BEARER_EXTRA_MAX))
      return buf;
   config_field_read(offsetof(config_t, server_api_bearer_extra) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_ensemble_reference_models(int index)
{
   static _Thread_local char buf[128];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_ENSEMBLE_MAX_REFS))
      return buf;
   config_field_read(offsetof(config_t, ensemble_reference_models) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_ensemble_reference_personas(int index)
{
   static _Thread_local char buf[64];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_ENSEMBLE_MAX_REFS))
      return buf;
   config_field_read(offsetof(config_t, ensemble_reference_personas) + (size_t)index * sizeof(buf),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

int config_set_db2_pool_size(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->db2_pool_size = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_workspace_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->workspace_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_subagent_ban_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->subagent_ban_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_embedder_dims(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->embedder_dims = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_maintenance_trigger_inserts(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_maintenance_trigger_inserts = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_maintenance_trigger_secs(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_maintenance_trigger_secs = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_maintenance_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_maintenance_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_maintenance_interval_seconds(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_maintenance_interval_seconds = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_maintenance_summarize_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_maintenance_summarize_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_code_cochange_git_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->code_cochange_git_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_wfe_proposals_autoscan_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->wfe_proposals_autoscan_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_client_integrations_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->client_integrations_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_audit_action_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->audit_action_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_salience_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_salience_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_salience_weight(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_salience_weight = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_salience_window_size(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_salience_window_size = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_surprise_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_surprise_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_surprise_weight(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_surprise_weight = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_coref_window(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_coref_window = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_cognify_async_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_cognify_async_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_cognify_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_cognify_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_context_budget_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_context_budget_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_context_budget_tokens(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_context_budget_tokens = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ingress_preinject_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->ingress_preinject_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ingress_preinject_anthropic_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->ingress_preinject_anthropic_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ingress_preinject_assembly_budget(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->ingress_preinject_assembly_budget = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ingress_max_raw_scans(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->ingress_max_raw_scans = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_code_span_max_lines(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->code_span_max_lines = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_tool_output_max_bytes(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->tool_output_max_bytes = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ingress_compress_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->ingress_compress_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ingress_compress_min_chars(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->ingress_compress_min_chars = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ingress_cache_placement_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->ingress_cache_placement_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_require_session_worktree(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->require_session_worktree = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_require_aimee_memory(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->require_aimee_memory = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_require_aimee_git(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->require_aimee_git = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_delegate_sandbox(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->delegate_sandbox = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_delegate_sandbox_require_isolation(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->delegate_sandbox_require_isolation = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_delegate_sandbox_learn_packages(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->delegate_sandbox_learn_packages = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_gateway_prevent_subagents(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->gateway_prevent_subagents = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_gateway_pin_model(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->gateway_pin_model = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_typed_facts_auto_promote_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_typed_facts_auto_promote_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_typed_facts_promote_threshold(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_typed_facts_promote_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_pdf_ingest_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_pdf_ingest_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_pdf_tsr_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_pdf_tsr_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_pdf_assets_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_pdf_assets_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_pdf_blob_recon_secs(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_pdf_blob_recon_secs = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_pdf_blob_orphan_alarm_mb(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_pdf_blob_orphan_alarm_mb = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_pdf_ocr_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_pdf_ocr_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_evidence_emit_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_evidence_emit_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_fidelity_check_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->fidelity_check_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_pagerank_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_pagerank_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_pagerank_iterations(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_pagerank_iterations = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_pagerank_weight(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_pagerank_weight = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_citations_reprompt_on_miss(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_citations_reprompt_on_miss = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_citations_strip_unverified(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_citations_strip_unverified = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_briefing_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_briefing_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_briefing_limit_tokens(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_briefing_limit_tokens = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_aggregation_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_aggregation_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_aggregation_max_items(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_aggregation_max_items = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_prospective_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_prospective_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_prospective_max_matches(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_prospective_max_matches = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_lifecycle_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_lifecycle_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_lifecycle_hide_archived(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_lifecycle_hide_archived = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_lifecycle_ttl_date_days(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_lifecycle_ttl_date_days = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_lifecycle_ttl_relative_days(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_lifecycle_ttl_relative_days = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_lifecycle_ttl_open_ended_days(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_lifecycle_ttl_open_ended_days = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_recall_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_recall_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_recall_limit_tokens_session(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_recall_limit_tokens_session = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_recall_limit_tokens_turn(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_recall_limit_tokens_turn = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_directives_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_directives_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_directives_failure_threshold(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_directives_failure_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_directives_max_matches(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_directives_max_matches = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_disposition_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->disposition_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_disposition_global_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->disposition_global_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_disposition_workspace_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->disposition_workspace_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_disposition_project_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->disposition_project_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_charter_safety_axioms_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->charter_safety_axioms_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_charter_hard_constraints_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->charter_hard_constraints_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_charter_values_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->charter_values_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_charter_tone_boundaries_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->charter_tone_boundaries_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_charter_working_profile_drift_limit(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->charter_working_profile_drift_limit = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_identity_working_profile_injection_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->identity_working_profile_injection_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_identity_working_profile_injection_fields_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->identity_working_profile_injection_fields_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_profile_cards_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_profile_cards_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_profile_cards_min_obs(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_profile_cards_min_obs = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_profile_cards_stale_secs(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_profile_cards_stale_secs = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_rewrite_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_rewrite_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_rewrite_hyde(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_rewrite_hyde = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_rewrite_decompose(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_rewrite_decompose = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_rewrite_max_subqueries(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_rewrite_max_subqueries = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_window_radius(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_window_radius = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_search_max_results(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_search_max_results = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_negation_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_negation_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_query_expansion_k(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->memory_query_expansion_k = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}
