/* Auto-generated by src/gen_config_accessors.py — do not edit directly.
 *
 * One accessor per config_t field. config_t is ~750 KB and its layout is a
 * config-module secret; callers outside the module ask for the value they
 * want and never name the type. Each reads a single field out of the live
 * snapshot under a reader pin, so a caller pays for one field rather than a
 * whole-struct copy.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "config.h"
#include "config_accessors.h"

/* Defined in config.c: reads one field out of the pinned snapshot, falling
 * back to a heap-loaded config when no snapshot is live. */
int config_field_read(size_t offset, size_t size, void *dst);

int config_set_guardrails_semantic_warn_threshold(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->guardrails_semantic_warn_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_guardrails_semantic_prompt_threshold(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->guardrails_semantic_prompt_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_guardrails_semantic_block_threshold(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->guardrails_semantic_block_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_api_http_port(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_api_http_port = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_synthesis_thinking(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->synthesis_thinking = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_server_api_http_port(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->server_api_http_port = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_server_api_tls_port(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->server_api_tls_port = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_server_api_mtls(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->server_api_mtls = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_server_api_bearer_extra_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->server_api_bearer_extra_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_server_api_rate_limit_per_min(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->server_api_rate_limit_per_min = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_server_api_max_event_streams(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->server_api_max_event_streams = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_server_api_cli_session_forwarding(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->server_api_cli_session_forwarding = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_server_api_remote_writes(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->server_api_remote_writes = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->calibration_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_buckets(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->calibration_buckets = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_prior_alpha0(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->calibration_prior_alpha0 = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_prior_beta0(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->calibration_prior_beta0 = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_credible_delta(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->calibration_credible_delta = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_conformal_window(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->calibration_conformal_window = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_conformal_epsilon(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->calibration_conformal_epsilon = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_tau_memory_auto(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->calibration_tau_memory_auto = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_tau_memory_flag(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->calibration_tau_memory_flag = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_tau_working_profile_auto(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->calibration_tau_working_profile_auto = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_tau_working_profile_flag(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->calibration_tau_working_profile_flag = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_demotion_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->demotion_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_demotion_window(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->demotion_window = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_demotion_half_life_days(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->demotion_half_life_days = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_demotion_n_min(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->demotion_n_min = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_fusion_static_alpha(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_fusion_static_alpha = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_ranker_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_ranker_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_ranker_fit_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_ranker_fit_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_ranker_fit_min_groups(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_ranker_fit_min_groups = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_ranker_fit_bench_k(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_ranker_fit_bench_k = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_reasoning_row_budget(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->reasoning_row_budget = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_reasoning_time_limit_ms(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->reasoning_time_limit_ms = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_bandit_exploration_fraction(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->bandit_exploration_fraction = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_bandit_ipw_weight_cap(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->bandit_ipw_weight_cap = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_bandit_exploration_window_seconds(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->bandit_exploration_window_seconds = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_planner_budget_default(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->planner_budget_default = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_planner_exploration_constant(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->planner_exploration_constant = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_mdl_tiebreak_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_mdl_tiebreak_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_mdl_bump_drift_alert(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_mdl_bump_drift_alert = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_synthesize_n_attempts(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_synthesize_n_attempts = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_reflection_synthesis_shadow(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_reflection_synthesis_shadow = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_worker_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_worker_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_db2_connection_pool_size(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->db2_connection_pool_size = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_connection_workers(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_connection_workers = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_bg_ingest_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_bg_ingest_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_bg_ingest_interval_hours(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_bg_ingest_interval_hours = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_bg_watch_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_bg_watch_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_bg_watch_debounce_secs(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_bg_watch_debounce_secs = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_code_hybrid_weight_code(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->code_hybrid_weight_code = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_code_hybrid_weight_graph(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->code_hybrid_weight_graph = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_code_hybrid_weight_vector(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->code_hybrid_weight_vector = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_code_hybrid_weight_memory(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->code_hybrid_weight_memory = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_code_hybrid_rrf_k(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->code_hybrid_rrf_k = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_code_trust_actuation_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->code_trust_actuation_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_code_surprising_precision_floor(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->code_surprising_precision_floor = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_reembed_on_dim_change(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_reembed_on_dim_change = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_purge_fence_ttl_s(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_purge_fence_ttl_s = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_maintenance_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_maintenance_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_maintenance_interval_hours(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_maintenance_interval_hours = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_maintenance_lambda(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_maintenance_lambda = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_maintenance_floor(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_maintenance_floor = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_maintenance_min_age_days(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_maintenance_min_age_days = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_maintenance_orphan_days(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_maintenance_orphan_days = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_mining_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_mining_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_mining_min_poll_s(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_mining_min_poll_s = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_mining_failure_learning_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_mining_failure_learning_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_trigger_max_concurrent(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->trigger_max_concurrent = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_trigger_rule_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->trigger_rule_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_cron_job_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->cron_job_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_review_scheduler_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->review_scheduler_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_review_idle_trigger_minutes(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->review_idle_trigger_minutes = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_review_session_cooldown_hours(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->review_session_cooldown_hours = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_review_batch_cap(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->review_batch_cap = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_extract_docs_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_extract_docs_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_extract_code_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_extract_code_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_extract_code_workers(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_extract_code_workers = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_extract_docs_workers(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_extract_docs_workers = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_resolve_entities_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_resolve_entities_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_index_narrative_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_index_narrative_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_index_claims_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_index_claims_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_detect_contradictions_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_detect_contradictions_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_index_code_unit_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_index_code_unit_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_link_artifacts_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_link_artifacts_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_projection_graph_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_projection_graph_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_synthesize_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_synthesize_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_promote_entity_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_promote_entity_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_promote_min_sources(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_promote_min_sources = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_extract_max_tokens(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_extract_max_tokens = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_max_attempts(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_max_attempts = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_synthesize_k(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_synthesize_k = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_cross_repo_graph_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_cross_repo_graph_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_cross_repo_distinctiveness_v(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_cross_repo_distinctiveness_v = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_cross_repo_k(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_cross_repo_k = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_cross_repo_m(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_cross_repo_m = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_cross_repo_p_pct(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_cross_repo_p_pct = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_cross_repo_len_min(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_cross_repo_len_min = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_cross_repo_caller_collision_c(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_cross_repo_caller_collision_c = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_cross_repo_max_candidates(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_cross_repo_max_candidates = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_cross_repo_query_timeout_ms(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_cross_repo_query_timeout_ms = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_cross_repo_review_queue_max(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_curator_cross_repo_review_queue_max = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_evidence_embed_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_evidence_embed_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_evidence_embed_batch(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->kb_evidence_embed_batch = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_skills_review_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->skills_review_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_skills_review_nudge_interval(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->skills_review_nudge_interval = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_skills_stale_after_days(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->skills_stale_after_days = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_skills_archive_after_days(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->skills_archive_after_days = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_skills_dispatch_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->skills_dispatch_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_skills_dispatch_max_index(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->skills_dispatch_max_index = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_skills_dispatch_advisory(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->skills_dispatch_advisory = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_skills_capability_autostub(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->skills_capability_autostub = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_skills_eval_gate_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->skills_eval_gate_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_skills_eval_threshold(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->skills_eval_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_worktree_gc_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->worktree_gc_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_worktree_gc_max_age_days(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->worktree_gc_max_age_days = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_aux_enabled(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->aux_enabled = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_aux_default_max_tokens(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->aux_default_max_tokens = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_aux_task_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->aux_task_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_prefer_local_agents(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->prefer_local_agents = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_model_meta_refresh_minutes(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->model_meta_refresh_minutes = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_model_meta_capability_routing(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->model_meta_capability_routing = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_db2_vector_corpus_diskann_threshold(int64_t value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->db2_vector_corpus_diskann_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ensemble_reference_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->ensemble_reference_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ensemble_reference_persona_count(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->ensemble_reference_persona_count = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ensemble_min_successful(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->ensemble_min_successful = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ensemble_max_cost_usd(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->ensemble_max_cost_usd = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_max_rounds(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_max_rounds = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_converge_threshold(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_converge_threshold = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_deadline_ms(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_deadline_ms = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_pipeline_max_passes(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_pipeline_max_passes = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_pipeline_max_attempts_per_pass(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_pipeline_max_attempts_per_pass = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_pipeline_max_cost_usd(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_pipeline_max_cost_usd = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_pipeline_max_total_cost_usd(double value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_pipeline_max_total_cost_usd = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_pipeline_gate_ttl_h(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_pipeline_gate_ttl_h = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_pipeline_parked_releases_slot(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_pipeline_parked_releases_slot = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_pipeline_unknown_context_tokens(int value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      cfg->roundtable_pipeline_unknown_context_tokens = value;
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_db1_path(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->db1_path, sizeof(cfg->db1_path), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}
