/* Auto-generated by src/gen_config_accessors.py — do not edit directly.
 *
 * One accessor per config_t field. config_t is ~750 KB and its layout is a
 * config-module secret; callers outside the module ask for the value they
 * want and never name the type. Each reads a single field out of the live
 * snapshot under a reader pin, so a caller pays for one field rather than a
 * whole-struct copy.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "config.h"
#include "config_accessors.h"

/* Defined in config.c: reads one field out of the pinned snapshot, falling
 * back to a heap-loaded config when no snapshot is live. */
int config_field_read(size_t offset, size_t size, void *dst);

int config_set_claude_model(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->claude_model, sizeof(cfg->claude_model), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_codex_model(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->codex_model, sizeof(cfg->codex_model), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_model_reasoning_effort(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->model_reasoning_effort, sizeof(cfg->model_reasoning_effort), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_openai_endpoint(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->openai_endpoint, sizeof(cfg->openai_endpoint), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_openai_model(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->openai_model, sizeof(cfg->openai_model), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_openai_key_cmd(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->openai_key_cmd, sizeof(cfg->openai_key_cmd), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_embedder_model(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->embedder_model, sizeof(cfg->embedder_model), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_embedder_url(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->embedder_url, sizeof(cfg->embedder_url), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_embedder_api_key(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->embedder_api_key, sizeof(cfg->embedder_api_key), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_weight_profile(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->memory_weight_profile, sizeof(cfg->memory_weight_profile), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_rerank_mode(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->memory_rerank_mode, sizeof(cfg->memory_rerank_mode), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_css_render_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->css_render_command, sizeof(cfg->css_render_command), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_vault_custody(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->vault_custody, sizeof(cfg->vault_custody), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_vault_tpm2_blob_path(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->vault_tpm2_blob_path, sizeof(cfg->vault_tpm2_blob_path), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_vault_tpm2_tcti(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->vault_tpm2_tcti, sizeof(cfg->vault_tpm2_tcti), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_vault_tpm2_nv_index(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->vault_tpm2_nv_index, sizeof(cfg->vault_tpm2_nv_index), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_coref_mode(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->memory_coref_mode, sizeof(cfg->memory_coref_mode), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_cognify_model(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->memory_cognify_model, sizeof(cfg->memory_cognify_model), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_cognify_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->memory_cognify_command, sizeof(cfg->memory_cognify_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_code_context_mode(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->code_context_mode, sizeof(cfg->code_context_mode), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_session_worktree_base(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->session_worktree_base, sizeof(cfg->session_worktree_base), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_delegate_sandbox_image(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->delegate_sandbox_image, sizeof(cfg->delegate_sandbox_image), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_delegate_sandbox_package_access(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->delegate_sandbox_package_access, sizeof(cfg->delegate_sandbox_package_access),
               "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_pdf_tier(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_pdf_tier, sizeof(cfg->kb_pdf_tier), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_tsr_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->tsr_command, sizeof(cfg->tsr_command), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_pdf_blob_dir(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_pdf_blob_dir, sizeof(cfg->kb_pdf_blob_dir), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ocr_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->ocr_command, sizeof(cfg->ocr_command), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_pagerank_relations(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->memory_pagerank_relations, sizeof(cfg->memory_pagerank_relations), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_citations_mode(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->memory_citations_mode, sizeof(cfg->memory_citations_mode), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_rewrite_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->memory_rewrite_command, sizeof(cfg->memory_rewrite_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_query_expansion_mode(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->memory_query_expansion_mode, sizeof(cfg->memory_query_expansion_mode), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_recall_lanes_summary_kinds(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->memory_recall_lanes_summary_kinds,
               sizeof(cfg->memory_recall_lanes_summary_kinds), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_recall_lanes_fact_kinds(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->memory_recall_lanes_fact_kinds, sizeof(cfg->memory_recall_lanes_fact_kinds),
               "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_memory_hard_negative_log(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->memory_hard_negative_log, sizeof(cfg->memory_hard_negative_log), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_dogfood_log_dir(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->dogfood_log_dir, sizeof(cfg->dogfood_log_dir), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_synthesize_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->learning_synthesize_command, sizeof(cfg->learning_synthesize_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_embed_model_version(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->learning_embed_model_version, sizeof(cfg->learning_embed_model_version), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_learning_synthesize_prompt_version(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->learning_synthesize_prompt_version,
               sizeof(cfg->learning_synthesize_prompt_version), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_verify_cmd(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->verify_cmd, sizeof(cfg->verify_cmd), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_verify_role(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->verify_role, sizeof(cfg->verify_role), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_verify_prompt(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->verify_prompt, sizeof(cfg->verify_prompt), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_search_backend(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->search_backend, sizeof(cfg->search_backend), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_search_searxng_url(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->search_searxng_url, sizeof(cfg->search_searxng_url), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_search_tavily_api_key(const char *value)
{
   return config_secret_store("AIMEE_SEARCH_TAVILY_API_KEY", value);
}

int config_set_search_backends(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->search_backends, sizeof(cfg->search_backends), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_coord_closet_denylist(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->coord_closet_denylist, sizeof(cfg->coord_closet_denylist), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_prompt_tier(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->prompt_tier, sizeof(cfg->prompt_tier), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_prompt_file(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->prompt_file, sizeof(cfg->prompt_file), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_delegate_prompt_tier(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->delegate_prompt_tier, sizeof(cfg->delegate_prompt_tier), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_otel_endpoint(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->otel_endpoint, sizeof(cfg->otel_endpoint), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_otel_service_name(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->otel_service_name, sizeof(cfg->otel_service_name), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_mcp_osv_endpoint(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->mcp_osv_endpoint, sizeof(cfg->mcp_osv_endpoint), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_computer_use_default_navigation(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->computer_use_default_navigation, sizeof(cfg->computer_use_default_navigation),
               "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_proxy_url(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->proxy_url, sizeof(cfg->proxy_url), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_proxy_token(const char *value)
{
   return config_secret_store("AIMEE_PROXY_TOKEN", value);
}

int config_set_ingress_trusted_proxy_secret(const char *value)
{
   return config_secret_store("AIMEE_INGRESS_PROXY_SECRET", value);
}

int config_set_guardrails_semantic_mode(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->guardrails_semantic_mode, sizeof(cfg->guardrails_semantic_mode), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_guardrails_semantic_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->guardrails_semantic_command, sizeof(cfg->guardrails_semantic_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_api_bearer_token(const char *value)
{
   return config_secret_store("AIMEE_KB_API_BEARER_TOKEN", value);
}

int config_set_telemetry_metrics_token(const char *value)
{
   return config_secret_store("AIMEE_TELEMETRY_METRICS_TOKEN", value);
}

int config_set_kb_client_url(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_client_url, sizeof(cfg->kb_client_url), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_client_bearer_token(const char *value)
{
   return config_secret_store("AIMEE_KB_API_BEARER_TOKEN", value);
}

int config_set_kb_mode(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_mode, sizeof(cfg->kb_mode), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_aimee_with_llamacpp(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->aimee_with_llamacpp, sizeof(cfg->aimee_with_llamacpp), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_aimee_synthesis_model(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->aimee_synthesis_model, sizeof(cfg->aimee_synthesis_model), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_synthesis_endpoint(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->synthesis_endpoint, sizeof(cfg->synthesis_endpoint), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_synthesis_model(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->synthesis_model, sizeof(cfg->synthesis_model), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_synthesis_api_key(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->synthesis_api_key, sizeof(cfg->synthesis_api_key), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_server_api_mtls_client_ca(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->server_api_mtls_client_ca, sizeof(cfg->server_api_mtls_client_ca), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_server_api_bearer_token(const char *value)
{
   return config_secret_store("AIMEE_API_BEARER_TOKEN", value);
}

int config_set_server_api_client_transport(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->server_api_client_transport, sizeof(cfg->server_api_client_transport), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->calibration_command, sizeof(cfg->calibration_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_prompt_version(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->calibration_prompt_version, sizeof(cfg->calibration_prompt_version), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_calibration_model_version(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->calibration_model_version, sizeof(cfg->calibration_model_version), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_fusion_mode(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_fusion_mode, sizeof(cfg->kb_fusion_mode), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ranker_fuse_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->ranker_fuse_command, sizeof(cfg->ranker_fuse_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_ranker_fit_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_ranker_fit_command, sizeof(cfg->kb_ranker_fit_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_ranker_fit_benchmark(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_ranker_fit_benchmark, sizeof(cfg->kb_ranker_fit_benchmark), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_ranker_fit_objective(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_ranker_fit_objective, sizeof(cfg->kb_ranker_fit_objective), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_reasoning_datalog_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->reasoning_datalog_command, sizeof(cfg->reasoning_datalog_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_bandit_optimize_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->bandit_optimize_command, sizeof(cfg->bandit_optimize_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_planner_search_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->planner_search_command, sizeof(cfg->planner_search_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_constraint_solver_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->constraint_solver_command, sizeof(cfg->constraint_solver_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_synthesize_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_synthesize_command, sizeof(cfg->kb_synthesize_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_trigger_auth_token(const char *value)
{
   return config_secret_store("AIMEE_TRIGGER_AUTH_TOKEN", value);
}

int config_set_kb_curator_tier(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_curator_tier, sizeof(cfg->kb_curator_tier), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_extract_prompt_version(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_curator_extract_prompt_version,
               sizeof(cfg->kb_curator_extract_prompt_version), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_embed_model_version(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_curator_embed_model_version, sizeof(cfg->kb_curator_embed_model_version),
               "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_invalidation_notify_socket(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_curator_invalidation_notify_socket,
               sizeof(cfg->kb_curator_invalidation_notify_socket), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_extract_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_curator_extract_command, sizeof(cfg->kb_curator_extract_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_stage_order(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_curator_stage_order, sizeof(cfg->kb_curator_stage_order), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_user_presets(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_curator_user_presets, sizeof(cfg->kb_curator_user_presets), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_custom_stages(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_curator_custom_stages, sizeof(cfg->kb_curator_custom_stages), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_provider_base_url(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_curator_provider_base_url, sizeof(cfg->kb_curator_provider_base_url), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_provider_model(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_curator_provider_model, sizeof(cfg->kb_curator_provider_model), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_provider_api_key(const char *value)
{
   return config_secret_store("AIMEE_KB_CURATOR_PROVIDER_API_KEY", value);
}

int config_set_kb_curator_judge_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_curator_judge_command, sizeof(cfg->kb_curator_judge_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_kb_curator_synthesize_command(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->kb_curator_synthesize_command, sizeof(cfg->kb_curator_synthesize_command), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_aux_default_provider(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->aux_default_provider, sizeof(cfg->aux_default_provider), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_aux_default_model(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->aux_default_model, sizeof(cfg->aux_default_model), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_db2_vector_corpus_index(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->db2_vector_corpus_index, sizeof(cfg->db2_vector_corpus_index), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_ensemble_aggregator(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->ensemble_aggregator, sizeof(cfg->ensemble_aggregator), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_turns(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->roundtable_turns, sizeof(cfg->roundtable_turns), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_default(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->roundtable_default, sizeof(cfg->roundtable_default), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_roundtable_pipeline_done_bar(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->roundtable_pipeline_done_bar, sizeof(cfg->roundtable_pipeline_done_bar), "%s",
               value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

int config_set_context_engine(const char *value)
{
   config_t *cfg = calloc(1, sizeof(*cfg));
   if (!cfg)
      return -1;
   int rc = config_load(cfg);
   if (rc == 0)
   {
      snprintf(cfg->context_engine, sizeof(cfg->context_engine), "%s", value ? value : "");
      rc = config_save(cfg);
   }
   free(cfg);
   return rc;
}

const char *config_cron_job_id(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->cron_jobs[0].id)];
   buf[0] = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return buf;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, id),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_cron_job_schedule(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->cron_jobs[0].schedule)];
   buf[0] = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return buf;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, schedule),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_cron_job_mode(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->cron_jobs[0].mode)];
   buf[0] = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return buf;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, mode),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_cron_job_script(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->cron_jobs[0].script)];
   buf[0] = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return buf;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, script),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_cron_job_prompt(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->cron_jobs[0].prompt)];
   buf[0] = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return buf;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, prompt),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_cron_job_workdir(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->cron_jobs[0].workdir)];
   buf[0] = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return buf;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, workdir),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_cron_job_context_from(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->cron_jobs[0].context_from)];
   buf[0] = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return buf;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, context_from),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_cron_job_when_context_contains(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->cron_jobs[0].when_context_contains)];
   buf[0] = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return buf;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, when_context_contains),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

int config_cron_job_skill_count(int index)
{
   int v = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return v;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, skill_count),
                     sizeof(v), &v);
   return v;
}

const char *config_cron_job_deliver_target(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->cron_jobs[0].deliver_target)];
   buf[0] = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return buf;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, deliver_target),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

int config_cron_job_deliver_only_if_changed(int index)
{
   int v = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return v;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, deliver_only_if_changed),
                     sizeof(v), &v);
   return v;
}

int config_cron_job_deliver_first_run_silent(int index)
{
   int v = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return v;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, deliver_first_run_silent),
                     sizeof(v), &v);
   return v;
}

int config_cron_job_pre_wake_gate(int index)
{
   int v = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return v;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, pre_wake_gate),
                     sizeof(v), &v);
   return v;
}

int config_cron_job_enabled(int index)
{
   int v = 0;
   if (index < 0 || index >= (CRON_JOBS_MAX))
      return v;
   config_field_read(offsetof(config_t, cron_jobs) +
                         (size_t)index * sizeof(((config_t *)0)->cron_jobs[0]) +
                         offsetof(cron_job_t, enabled),
                     sizeof(v), &v);
   return v;
}

const char *config_disposition_name(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->dispositions[0].name)];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_MAX_DISPOSITIONS))
      return buf;
   config_field_read(offsetof(config_t, dispositions) +
                         (size_t)index * sizeof(((config_t *)0)->dispositions[0]) +
                         offsetof(config_disposition_t, name),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

double config_disposition_value(int index)
{
   double v = 0;
   if (index < 0 || index >= (CONFIG_MAX_DISPOSITIONS))
      return v;
   config_field_read(offsetof(config_t, dispositions) +
                         (size_t)index * sizeof(((config_t *)0)->dispositions[0]) +
                         offsetof(config_disposition_t, value),
                     sizeof(v), &v);
   return v;
}

const char *config_mcp_client_name(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->mcp_clients[0].name)];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_MCP_MAX_CLIENTS))
      return buf;
   config_field_read(offsetof(config_t, mcp_clients) +
                         (size_t)index * sizeof(((config_t *)0)->mcp_clients[0]) +
                         offsetof(config_mcp_client_t, name),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

int config_mcp_client_command_count(int index)
{
   int v = 0;
   if (index < 0 || index >= (CONFIG_MCP_MAX_CLIENTS))
      return v;
   config_field_read(offsetof(config_t, mcp_clients) +
                         (size_t)index * sizeof(((config_t *)0)->mcp_clients[0]) +
                         offsetof(config_mcp_client_t, command_count),
                     sizeof(v), &v);
   return v;
}

const char *config_mcp_client_cwd(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->mcp_clients[0].cwd)];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_MCP_MAX_CLIENTS))
      return buf;
   config_field_read(offsetof(config_t, mcp_clients) +
                         (size_t)index * sizeof(((config_t *)0)->mcp_clients[0]) +
                         offsetof(config_mcp_client_t, cwd),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_mcp_client_url(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->mcp_clients[0].url)];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_MCP_MAX_CLIENTS))
      return buf;
   config_field_read(offsetof(config_t, mcp_clients) +
                         (size_t)index * sizeof(((config_t *)0)->mcp_clients[0]) +
                         offsetof(config_mcp_client_t, url),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_mcp_client_bearer_token_env(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->mcp_clients[0].bearer_token_env)];
   buf[0] = 0;
   if (index < 0 || index >= (CONFIG_MCP_MAX_CLIENTS))
      return buf;
   config_field_read(offsetof(config_t, mcp_clients) +
                         (size_t)index * sizeof(((config_t *)0)->mcp_clients[0]) +
                         offsetof(config_mcp_client_t, bearer_token_env),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_trigger_rule_source(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->trigger_rules[0].source)];
   buf[0] = 0;
   if (index < 0 || index >= (TRIGGER_RULES_MAX))
      return buf;
   config_field_read(offsetof(config_t, trigger_rules) +
                         (size_t)index * sizeof(((config_t *)0)->trigger_rules[0]) +
                         offsetof(trigger_rule_t, source),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_trigger_rule_event(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->trigger_rules[0].event)];
   buf[0] = 0;
   if (index < 0 || index >= (TRIGGER_RULES_MAX))
      return buf;
   config_field_read(offsetof(config_t, trigger_rules) +
                         (size_t)index * sizeof(((config_t *)0)->trigger_rules[0]) +
                         offsetof(trigger_rule_t, event),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_trigger_rule_schedule(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->trigger_rules[0].schedule)];
   buf[0] = 0;
   if (index < 0 || index >= (TRIGGER_RULES_MAX))
      return buf;
   config_field_read(offsetof(config_t, trigger_rules) +
                         (size_t)index * sizeof(((config_t *)0)->trigger_rules[0]) +
                         offsetof(trigger_rule_t, schedule),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_trigger_rule_pipeline_template(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->trigger_rules[0].pipeline_template)];
   buf[0] = 0;
   if (index < 0 || index >= (TRIGGER_RULES_MAX))
      return buf;
   config_field_read(offsetof(config_t, trigger_rules) +
                         (size_t)index * sizeof(((config_t *)0)->trigger_rules[0]) +
                         offsetof(trigger_rule_t, pipeline_template),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_trigger_rule_workspace(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->trigger_rules[0].workspace)];
   buf[0] = 0;
   if (index < 0 || index >= (TRIGGER_RULES_MAX))
      return buf;
   config_field_read(offsetof(config_t, trigger_rules) +
                         (size_t)index * sizeof(((config_t *)0)->trigger_rules[0]) +
                         offsetof(trigger_rule_t, workspace),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

const char *config_trigger_rule_mode(int index)
{
   static _Thread_local char buf[sizeof(((config_t *)0)->trigger_rules[0].mode)];
   buf[0] = 0;
   if (index < 0 || index >= (TRIGGER_RULES_MAX))
      return buf;
   config_field_read(offsetof(config_t, trigger_rules) +
                         (size_t)index * sizeof(((config_t *)0)->trigger_rules[0]) +
                         offsetof(trigger_rule_t, mode),
                     sizeof(buf), buf);
   buf[sizeof(buf) - 1] = 0;
   return buf;
}

double config_trigger_rule_max_spend_usd(int index)
{
   double v = 0;
   if (index < 0 || index >= (TRIGGER_RULES_MAX))
      return v;
   config_field_read(offsetof(config_t, trigger_rules) +
                         (size_t)index * sizeof(((config_t *)0)->trigger_rules[0]) +
                         offsetof(trigger_rule_t, max_spend_usd),
                     sizeof(v), &v);
   return v;
}
