/* Auto-generated by src/gen_config_accessors.py — do not edit directly.
 *
 * One accessor per config_t field. config_t is ~750 KB and its layout is a
 * config-module secret; callers outside the module ask for the value they
 * want and never name the type. Each reads a single field out of the live
 * snapshot under a reader pin, so a caller pays for one field rather than a
 * whole-struct copy.
 */

#include <stddef.h>
#include <stdio.h>
#include <string.h>

#include "config.h"
#include "config_accessors.h"

/* Defined in config.c: reads one field out of the pinned snapshot, falling
 * back to a heap-loaded config when no snapshot is live. */
int config_field_read(size_t offset, size_t size, void *dst);

int config_cross_verify(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, cross_verify), sizeof(v), &v);
   return v;
}

int config_retry_max_attempts(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, retry_max_attempts), sizeof(v), &v);
   return v;
}

int config_retry_base_ms(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, retry_base_ms), sizeof(v), &v);
   return v;
}

int config_retry_max_ms(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, retry_max_ms), sizeof(v), &v);
   return v;
}

int config_max_iterations(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, max_iterations), sizeof(v), &v);
   return v;
}

int config_max_iterations_delegate(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, max_iterations_delegate), sizeof(v), &v);
   return v;
}

int config_max_delegation_depth(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, max_delegation_depth), sizeof(v), &v);
   return v;
}

int config_max_delegation_spawns(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, max_delegation_spawns), sizeof(v), &v);
   return v;
}

int config_compute_threads(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, compute_threads), sizeof(v), &v);
   return v;
}

int config_session_threads(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, session_threads), sizeof(v), &v);
   return v;
}

int config_delegate_max_inflight(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, delegate_max_inflight), sizeof(v), &v);
   return v;
}

int config_maximum_total_concurrent_agent_sessions(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, maximum_total_concurrent_agent_sessions), sizeof(v), &v);
   return v;
}

int config_concurrency_default(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, concurrency_default), sizeof(v), &v);
   return v;
}

int config_concurrency_per_model_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, concurrency_per_model_count), sizeof(v), &v);
   return v;
}

int config_concurrency_per_provider_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, concurrency_per_provider_count), sizeof(v), &v);
   return v;
}

int config_concurrency_preempt_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, concurrency_preempt_enabled), sizeof(v), &v);
   return v;
}

int config_concurrency_preempt_single_slot_only(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, concurrency_preempt_single_slot_only), sizeof(v), &v);
   return v;
}

int config_concurrency_preempt_requeue_max(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, concurrency_preempt_requeue_max), sizeof(v), &v);
   return v;
}

int config_search_max_results(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, search_max_results), sizeof(v), &v);
   return v;
}

int config_search_fetch_pages(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, search_fetch_pages), sizeof(v), &v);
   return v;
}

int config_compact_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, compact_enabled), sizeof(v), &v);
   return v;
}

int config_compact_threshold(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, compact_threshold), sizeof(v), &v);
   return v;
}

int config_compact_head_bytes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, compact_head_bytes), sizeof(v), &v);
   return v;
}

int config_compact_tail_bytes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, compact_tail_bytes), sizeof(v), &v);
   return v;
}

int config_compact_per_tool_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, compact_per_tool_count), sizeof(v), &v);
   return v;
}

int config_coord_closet_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, coord_closet_enabled), sizeof(v), &v);
   return v;
}

int config_coord_closet_budget_bytes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, coord_closet_budget_bytes), sizeof(v), &v);
   return v;
}

int config_coord_closet_max_ratio_pct(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, coord_closet_max_ratio_pct), sizeof(v), &v);
   return v;
}

int config_fold_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, fold_enabled), sizeof(v), &v);
   return v;
}

int config_fold_retained_msgs(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, fold_retained_msgs), sizeof(v), &v);
   return v;
}

int config_fold_min_fold_msgs(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, fold_min_fold_msgs), sizeof(v), &v);
   return v;
}

int config_fold_excerpt_bytes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, fold_excerpt_bytes), sizeof(v), &v);
   return v;
}

int config_fold_register_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, fold_register_enabled), sizeof(v), &v);
   return v;
}

int config_fold_freeze_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, fold_freeze_enabled), sizeof(v), &v);
   return v;
}

int config_fold_freeze_tail_cap_msgs(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, fold_freeze_tail_cap_msgs), sizeof(v), &v);
   return v;
}

int config_fold_recall_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, fold_recall_enabled), sizeof(v), &v);
   return v;
}

int config_fold_recall_ttl_turns(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, fold_recall_ttl_turns), sizeof(v), &v);
   return v;
}

int config_economizer_mode(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, economizer_mode), sizeof(v), &v);
   return v;
}

int config_module_memory(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, module_memory), sizeof(v), &v);
   return v;
}

int config_module_governance(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, module_governance), sizeof(v), &v);
   return v;
}

int config_module_delegates(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, module_delegates), sizeof(v), &v);
   return v;
}

int config_module_workflows(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, module_workflows), sizeof(v), &v);
   return v;
}

int config_module_roundtable(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, module_roundtable), sizeof(v), &v);
   return v;
}

int config_module_economizer(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, module_economizer), sizeof(v), &v);
   return v;
}

int config_autonomy_skeptics(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, autonomy_skeptics), sizeof(v), &v);
   return v;
}

int config_autonomy_fanout(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, autonomy_fanout), sizeof(v), &v);
   return v;
}

int config_autonomy_unit_retry(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, autonomy_unit_retry), sizeof(v), &v);
   return v;
}

int config_autonomy_unit_max(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, autonomy_unit_max), sizeof(v), &v);
   return v;
}

int config_autonomy_ci_retry_max(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, autonomy_ci_retry_max), sizeof(v), &v);
   return v;
}

int config_autonomy_max_turns(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, autonomy_max_turns), sizeof(v), &v);
   return v;
}

int config_autonomy_max_wall_secs(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, autonomy_max_wall_secs), sizeof(v), &v);
   return v;
}

int config_autonomy_stale_abandon_secs(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, autonomy_stale_abandon_secs), sizeof(v), &v);
   return v;
}

int config_autonomy_concurrency(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, autonomy_concurrency), sizeof(v), &v);
   return v;
}

int config_autonomy_auto_resume_cap_parks(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, autonomy_auto_resume_cap_parks), sizeof(v), &v);
   return v;
}

int config_autonomy_max_resumes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, autonomy_max_resumes), sizeof(v), &v);
   return v;
}

int config_worktree_stale_secs(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, worktree_stale_secs), sizeof(v), &v);
   return v;
}

int config_max_sessions(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, max_sessions), sizeof(v), &v);
   return v;
}

int config_max_worktrees(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, max_worktrees), sizeof(v), &v);
   return v;
}

int config_max_background_processes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, max_background_processes), sizeof(v), &v);
   return v;
}

int config_rewind_auto_snapshot(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, rewind_auto_snapshot), sizeof(v), &v);
   return v;
}

int config_lsp_server_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, lsp_server_count), sizeof(v), &v);
   return v;
}

int config_mcp_client_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, mcp_client_count), sizeof(v), &v);
   return v;
}

int config_mcp_osv_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, mcp_osv_enabled), sizeof(v), &v);
   return v;
}

int config_mcp_osv_offline(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, mcp_osv_offline), sizeof(v), &v);
   return v;
}

int config_mcp_osv_enforce(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, mcp_osv_enforce), sizeof(v), &v);
   return v;
}

int config_mcp_osv_cache_ttl_hours(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, mcp_osv_cache_ttl_hours), sizeof(v), &v);
   return v;
}

int config_mcp_osv_allow_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, mcp_osv_allow_count), sizeof(v), &v);
   return v;
}

int config_computer_use_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, computer_use_enabled), sizeof(v), &v);
   return v;
}

int config_computer_use_redact_sensitive_screenshots(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, computer_use_redact_sensitive_screenshots), sizeof(v), &v);
   return v;
}

int config_computer_use_allowed_domain_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, computer_use_allowed_domain_count), sizeof(v), &v);
   return v;
}

int config_integrity_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, integrity_enabled), sizeof(v), &v);
   return v;
}

int config_integrity_dry_run(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, integrity_dry_run), sizeof(v), &v);
   return v;
}

int config_virtual_context_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, virtual_context_enabled), sizeof(v), &v);
   return v;
}

int config_virtual_context_assembly_budget(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, virtual_context_assembly_budget), sizeof(v), &v);
   return v;
}

int config_cache_aware_rewrite_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, cache_aware_rewrite_enabled), sizeof(v), &v);
   return v;
}

int config_cache_aware_rewrite_min_savings_tokens(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, cache_aware_rewrite_min_savings_tokens), sizeof(v), &v);
   return v;
}

double config_cache_aware_rewrite_hard_context_threshold(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, cache_aware_rewrite_hard_context_threshold), sizeof(v), &v);
   return v;
}

int config_cache_aware_rewrite_max_defer_turns(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, cache_aware_rewrite_max_defer_turns), sizeof(v), &v);
   return v;
}

int config_cache_aware_rewrite_segment_check_turns(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, cache_aware_rewrite_segment_check_turns), sizeof(v), &v);
   return v;
}

int config_transport_server_keepalive_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, transport_server_keepalive_enabled), sizeof(v), &v);
   return v;
}

int config_transport_thinclient_gzip_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, transport_thinclient_gzip_enabled), sizeof(v), &v);
   return v;
}

int config_transport_kb_gzip_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, transport_kb_gzip_enabled), sizeof(v), &v);
   return v;
}

int config_cost_reward_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, cost_reward_enabled), sizeof(v), &v);
   return v;
}

int config_cost_reward_lambda_pct(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, cost_reward_lambda_pct), sizeof(v), &v);
   return v;
}

int config_cost_reward_ref_usd_milli(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, cost_reward_ref_usd_milli), sizeof(v), &v);
   return v;
}

int config_reasoning_cap_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, reasoning_cap_enabled), sizeof(v), &v);
   return v;
}

int config_dedup_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, dedup_enabled), sizeof(v), &v);
   return v;
}

int config_cache_shaping_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, cache_shaping_enabled), sizeof(v), &v);
   return v;
}

int config_dedup_window_seconds(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, dedup_window_seconds), sizeof(v), &v);
   return v;
}

int config_cache_min_chars(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, cache_min_chars), sizeof(v), &v);
   return v;
}

double config_guardrails_semantic_warn_threshold(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, guardrails_semantic_warn_threshold), sizeof(v), &v);
   return v;
}

double config_guardrails_semantic_prompt_threshold(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, guardrails_semantic_prompt_threshold), sizeof(v), &v);
   return v;
}

double config_guardrails_semantic_block_threshold(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, guardrails_semantic_block_threshold), sizeof(v), &v);
   return v;
}

int config_kb_api_http_port(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_api_http_port), sizeof(v), &v);
   return v;
}

int config_synthesis_thinking(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, synthesis_thinking), sizeof(v), &v);
   return v;
}

int config_server_api_http_port(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, server_api_http_port), sizeof(v), &v);
   return v;
}

int config_server_api_tls_port(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, server_api_tls_port), sizeof(v), &v);
   return v;
}

int config_server_api_mtls(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, server_api_mtls), sizeof(v), &v);
   return v;
}

int config_server_api_bearer_extra_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, server_api_bearer_extra_count), sizeof(v), &v);
   return v;
}

int config_server_api_rate_limit_per_min(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, server_api_rate_limit_per_min), sizeof(v), &v);
   return v;
}

int config_server_api_max_event_streams(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, server_api_max_event_streams), sizeof(v), &v);
   return v;
}

int config_server_api_cli_session_forwarding(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, server_api_cli_session_forwarding), sizeof(v), &v);
   return v;
}

int config_server_api_remote_writes(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, server_api_remote_writes), sizeof(v), &v);
   return v;
}

int config_calibration_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, calibration_enabled), sizeof(v), &v);
   return v;
}

int config_calibration_buckets(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, calibration_buckets), sizeof(v), &v);
   return v;
}

double config_calibration_prior_alpha0(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, calibration_prior_alpha0), sizeof(v), &v);
   return v;
}

double config_calibration_prior_beta0(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, calibration_prior_beta0), sizeof(v), &v);
   return v;
}

double config_calibration_credible_delta(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, calibration_credible_delta), sizeof(v), &v);
   return v;
}

int config_calibration_conformal_window(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, calibration_conformal_window), sizeof(v), &v);
   return v;
}

double config_calibration_conformal_epsilon(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, calibration_conformal_epsilon), sizeof(v), &v);
   return v;
}

double config_calibration_tau_memory_auto(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, calibration_tau_memory_auto), sizeof(v), &v);
   return v;
}

double config_calibration_tau_memory_flag(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, calibration_tau_memory_flag), sizeof(v), &v);
   return v;
}

double config_calibration_tau_working_profile_auto(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, calibration_tau_working_profile_auto), sizeof(v), &v);
   return v;
}

double config_calibration_tau_working_profile_flag(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, calibration_tau_working_profile_flag), sizeof(v), &v);
   return v;
}

int config_demotion_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, demotion_enabled), sizeof(v), &v);
   return v;
}

int config_demotion_window(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, demotion_window), sizeof(v), &v);
   return v;
}

double config_demotion_half_life_days(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, demotion_half_life_days), sizeof(v), &v);
   return v;
}

int config_demotion_n_min(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, demotion_n_min), sizeof(v), &v);
   return v;
}

double config_kb_fusion_static_alpha(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, kb_fusion_static_alpha), sizeof(v), &v);
   return v;
}

int config_kb_ranker_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_ranker_enabled), sizeof(v), &v);
   return v;
}

int config_kb_ranker_fit_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_ranker_fit_enabled), sizeof(v), &v);
   return v;
}

int config_kb_ranker_fit_min_groups(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_ranker_fit_min_groups), sizeof(v), &v);
   return v;
}

int config_kb_ranker_fit_bench_k(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_ranker_fit_bench_k), sizeof(v), &v);
   return v;
}

int config_reasoning_row_budget(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, reasoning_row_budget), sizeof(v), &v);
   return v;
}

int config_reasoning_time_limit_ms(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, reasoning_time_limit_ms), sizeof(v), &v);
   return v;
}

double config_bandit_exploration_fraction(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, bandit_exploration_fraction), sizeof(v), &v);
   return v;
}

double config_bandit_ipw_weight_cap(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, bandit_ipw_weight_cap), sizeof(v), &v);
   return v;
}

int config_bandit_exploration_window_seconds(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, bandit_exploration_window_seconds), sizeof(v), &v);
   return v;
}

int config_planner_budget_default(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, planner_budget_default), sizeof(v), &v);
   return v;
}

double config_planner_exploration_constant(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, planner_exploration_constant), sizeof(v), &v);
   return v;
}

int config_kb_mdl_tiebreak_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_mdl_tiebreak_enabled), sizeof(v), &v);
   return v;
}

double config_kb_mdl_bump_drift_alert(void)
{
   double v = 0;
   config_field_read(offsetof(config_t, kb_mdl_bump_drift_alert), sizeof(v), &v);
   return v;
}

int config_kb_synthesize_n_attempts(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_synthesize_n_attempts), sizeof(v), &v);
   return v;
}

int config_kb_reflection_synthesis_shadow(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_reflection_synthesis_shadow), sizeof(v), &v);
   return v;
}

int config_kb_worker_count(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_worker_count), sizeof(v), &v);
   return v;
}

int config_db2_connection_pool_size(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, db2_connection_pool_size), sizeof(v), &v);
   return v;
}

int config_kb_connection_workers(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_connection_workers), sizeof(v), &v);
   return v;
}

int config_kb_bg_ingest_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_bg_ingest_enabled), sizeof(v), &v);
   return v;
}

int config_kb_bg_ingest_interval_hours(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_bg_ingest_interval_hours), sizeof(v), &v);
   return v;
}

int config_kb_bg_watch_enabled(void)
{
   int v = 0;
   config_field_read(offsetof(config_t, kb_bg_watch_enabled), sizeof(v), &v);
   return v;
}
